services:
  - type: web
    name: aeterna
    runtime: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: APP_NAME
        value: AeternaX
      - key: APP_ENV
        value: production
      - key: APP_URL
        value: https://aeterna-0mp0.onrender.com
      - key: APP_DEBUG
        value: false
      - key: APP_KEY
        generateValue: true
      - key: DB_CONNECTION
        value: pgsql
      - key: DATABASE_URL
        sync: false
      - key: SESSION_DRIVER
        value: cookie
      - key: SESSION_LIFETIME
        value: 120
      - key: CACHE_STORE
        value: array
      - key: QUEUE_CONNECTION
        value: sync
      - key: LOG_CHANNEL
        value: stderr
      - key: LOG_LEVEL
        value: error
